---
# This the deployment YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tekton1
  name: tekton1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tekton1
    spec:
      containers:
      - image: davekrier/tekton1:latest
        name: tekton1
        resources: {}
status: {}
---
# This the service yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton1
  name: tekton1-svc
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: tekton1
  type: LoadBalancer
