apiVersion: v1
kind: Secret
metadata:
  name: tekton-git
  namespace: tekton-lab
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    service-account: tekton-docker-sa
type: kubernetes.io/basic-auth
stringData:
  namespace: tekton-lab
  username: <username>
  password: <token>