apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton1
  name: testingsvc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tekton1
  type: LoadBalancer
